// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Cheap_Yello_Display_demo

#ifndef _CHEAP_YELLO_DISPLAY_DEMO_UI_H
#define _CHEAP_YELLO_DISPLAY_DEMO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void bouncingball_Animation(lv_obj_t * TargetObject, int delay);
void takeFoto_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_Label3;
void ui_event_goConfSc(lv_event_t * e);
extern lv_obj_t * ui_goConfSc;
extern lv_obj_t * ui_Label4;
void ui_event_goMovSc(lv_event_t * e);
extern lv_obj_t * ui_goMovSc;
extern lv_obj_t * ui_Label5;
void ui_event_goScreen3(lv_event_t * e);
extern lv_obj_t * ui_goScreen3;
extern lv_obj_t * ui_goCapSc;
extern lv_obj_t * ui_wifiIcon;
// SCREEN: ui_confScreen
void ui_confScreen_screen_init(void);
extern lv_obj_t * ui_confScreen;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Label1;
void ui_event_camType(lv_event_t * e);
extern lv_obj_t * ui_camType;
extern lv_obj_t * ui_endStopCheck;
extern lv_obj_t * ui_autoLigthCheck;
void ui_event_updateButton(lv_event_t * e);
extern lv_obj_t * ui_updateButton;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_versionLabel;
void ui_event_wifiButton(lv_event_t * e);
extern lv_obj_t * ui_wifiButton;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_canonTimeContainer;
extern lv_obj_t * ui_canonTimeLabel;
void ui_event_canonTimeSlider(lv_event_t * e);
extern lv_obj_t * ui_canonTimeSlider;
extern lv_obj_t * ui_canonTimeText;
// SCREEN: ui_movScreen
void ui_movScreen_screen_init(void);
extern lv_obj_t * ui_movScreen;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Label7;
void ui_event_dropDownDistMov(lv_event_t * e);
extern lv_obj_t * ui_dropDownDistMov;
extern lv_obj_t * ui_Label9;
void ui_event_ImgButton4(lv_event_t * e);
extern lv_obj_t * ui_ImgButton4;
void ui_event_ImgButton5(lv_event_t * e);
extern lv_obj_t * ui_ImgButton5;
extern lv_obj_t * ui_movLabel;
void ui_event_ImgButton6(lv_event_t * e);
extern lv_obj_t * ui_ImgButton6;
// SCREEN: ui_captScreen
void ui_captScreen_screen_init(void);
extern lv_obj_t * ui_captScreen;
void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_capProfLabel;
extern lv_obj_t * ui_capFotLabel;
extern lv_obj_t * ui_capTimeLabel;
void ui_event_capProfSlider(lv_event_t * e);
extern lv_obj_t * ui_capProfSlider;
void ui_event_capFotSlider(lv_event_t * e);
extern lv_obj_t * ui_capFotSlider;
void ui_event_capTimeSlider(lv_event_t * e);
extern lv_obj_t * ui_capTimeSlider;
void ui_event_startButton(lv_event_t * e);
extern lv_obj_t * ui_startButton;
extern lv_obj_t * ui_Label13;
// SCREEN: ui_updateScreen
void ui_updateScreen_screen_init(void);
void ui_event_updateScreen(lv_event_t * e);
extern lv_obj_t * ui_updateScreen;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_updateBar;
// SCREEN: ui_wifiScreen
void ui_wifiScreen_screen_init(void);
void ui_event_wifiScreen(lv_event_t * e);
extern lv_obj_t * ui_wifiScreen;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_ssidDropdown;
extern lv_obj_t * ui_Label6;
void ui_event_Image3(lv_event_t * e);
extern lv_obj_t * ui_Image3;
void ui_event_wifiKeyboard(lv_event_t * e);
extern lv_obj_t * ui_wifiKeyboard;
extern lv_obj_t * ui_Label8;
void ui_event_passTextarea(lv_event_t * e);
extern lv_obj_t * ui_passTextarea;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_wifi32_png);    // assets/wifi32.png
LV_IMG_DECLARE(ui_img_home_png);    // assets/home.png
LV_IMG_DECLARE(ui_img_388382192);    // assets/left-arrow.png
LV_IMG_DECLARE(ui_img_1101766569);    // assets/right-arrow.png
LV_IMG_DECLARE(ui_img_885855874);    // assets/stop-button.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
