// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: demo5

#include <Arduino.h>
#include "ui.h"
#include "stdio.h"
#include "RGBledDriver.h"

int indx = 1;
char buf[3];

void Button1PressedAction(lv_event_t *e)
{
	int newColor;
	indx++;

	sprintf(buf, "%d", indx);
	lv_textarea_set_placeholder_text(ui_TextArea1, buf);

	if (indx == 1)
	{

		newColor = RGB_COLOR_1;
		lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(newColor), LV_PART_MAIN);
		ChangeRGBColor(newColor);
	}

	else if (indx == 2)
	{
		newColor = RGB_COLOR_2;
		lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(newColor), LV_PART_MAIN);
		ChangeRGBColor(newColor);
	}

	else if (indx == 3)
	{
		newColor = RGB_COLOR_3;
		lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(newColor), LV_PART_MAIN);
		ChangeRGBColor(newColor);
	}

	else if (indx == 4)
	{
		newColor = RGB_COLOR_4;
		lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(newColor), LV_PART_MAIN);
		ChangeRGBColor(newColor);
	}

	else if (indx == 5)
	{
		newColor = RGB_COLOR_5;
		lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(newColor), LV_PART_MAIN);
		ChangeRGBColor(newColor);
		indx = 0;
	}
	
}
