// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Cheap_Yello_Display_demo

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void setCamType(lv_event_t * e);
void doOtaUpdate(lv_event_t * e);
void movDistChange(lv_event_t * e);
void movBackward(lv_event_t * e);
void movForward(lv_event_t * e);
void setCapProf(lv_event_t * e);
void setCapFotos(lv_event_t * e);
void setCapTime(lv_event_t * e);
void startCapture(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
