// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: demo5

#ifndef _UI_COMP_SCREEN_1_H
#define _UI_COMP_SCREEN_1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Screen 1
#define UI_COMP_SCREEN_1_SCREEN_1 0
#define _UI_COMP_SCREEN_1_NUM 1
lv_obj_t * ui_Screen_1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
