// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Cheap_Yello_Display_demo

#ifndef _UI_COMP_LABEL16_H
#define _UI_COMP_LABEL16_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Label16
#define UI_COMP_LABEL16_LABEL16 0
#define _UI_COMP_LABEL16_NUM 1
lv_obj_t * ui_Label16_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
