// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Cheap_Yello_Display_demo

#include "../ui.h"


// COMPONENT Label16

lv_obj_t * ui_Label16_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Label16;
    cui_Label16 = lv_label_create(comp_parent);
    lv_obj_set_width(cui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label16, -55);
    lv_obj_set_y(cui_Label16, -4);
    lv_obj_set_align(cui_Label16, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LABEL16_NUM);
    children[UI_COMP_LABEL16_LABEL16] = cui_Label16;
    lv_obj_add_event_cb(cui_Label16, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Label16, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Label16_create_hook(cui_Label16);
    return cui_Label16;
}

