// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Cheap_Yello_Display_demo

#ifndef _UI_COMP_SCREEN1_H
#define _UI_COMP_SCREEN1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Screen1
#define UI_COMP_SCREEN1_SCREEN1 0
#define _UI_COMP_SCREEN1_NUM 1
lv_obj_t * ui_Screen1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
