// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Cheap_Yello_Display_demo

#include "../ui.h"

void ui_captScreen_screen_init(void)
{
    ui_captScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_captScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_captScreen, lv_color_hex(0x8BEAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_captScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton3 = lv_imgbtn_create(ui_captScreen);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_png, NULL);
    lv_obj_set_height(ui_ImgButton3, 36);
    lv_obj_set_width(ui_ImgButton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton3, 125);
    lv_obj_set_y(ui_ImgButton3, 88);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);

    ui_Label8 = lv_label_create(ui_captScreen);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -7);
    lv_obj_set_y(ui_Label8, -90);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Captura");

    ui_TabView1 = lv_tabview_create(ui_captScreen, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 100);
    lv_obj_set_height(ui_TabView1, 200);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);

}
