// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Cheap_Yello_Display_demo

#include "../ui.h"

void ui_confScreen_screen_init(void)
{
    ui_confScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_confScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_confScreen, lv_color_hex(0x8BEAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_confScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_imgbtn_create(ui_confScreen);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_png, NULL);
    lv_obj_set_height(ui_ImgButton1, 36);
    lv_obj_set_width(ui_ImgButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton1, 125);
    lv_obj_set_y(ui_ImgButton1, 88);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_confScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -79);
    lv_obj_set_y(ui_Label1, -92);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Camara");

    ui_camType = lv_dropdown_create(ui_confScreen);
    lv_dropdown_set_options(ui_camType, "Canon\nNikon\nOlympus\nPentax\nSony\nMinolta");
    lv_obj_set_width(ui_camType, 150);
    lv_obj_set_height(ui_camType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_camType, 58);
    lv_obj_set_y(ui_camType, -92);
    lv_obj_set_align(ui_camType, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_camType, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_endStopCheck = lv_checkbox_create(ui_confScreen);
    lv_checkbox_set_text(ui_endStopCheck, "Final Carrera");
    lv_obj_set_width(ui_endStopCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_endStopCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_endStopCheck, -78);
    lv_obj_set_y(ui_endStopCheck, 24);
    lv_obj_set_align(ui_endStopCheck, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_endStopCheck, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_endStopCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_autoLigthCheck = lv_checkbox_create(ui_confScreen);
    lv_checkbox_set_text(ui_autoLigthCheck, "Auto Ligth");
    lv_obj_set_width(ui_autoLigthCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_autoLigthCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_autoLigthCheck, 65);
    lv_obj_set_y(ui_autoLigthCheck, 23);
    lv_obj_set_align(ui_autoLigthCheck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_autoLigthCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_updateButton = lv_btn_create(ui_confScreen);
    lv_obj_set_width(ui_updateButton, 72);
    lv_obj_set_height(ui_updateButton, 41);
    lv_obj_set_x(ui_updateButton, -103);
    lv_obj_set_y(ui_updateButton, 82);
    lv_obj_set_align(ui_updateButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_updateButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_updateButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_updateButton);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -1);
    lv_obj_set_y(ui_Label2, 1);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Update");

    ui_versionLabel = lv_label_create(ui_confScreen);
    lv_obj_set_width(ui_versionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_versionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_versionLabel, 59);
    lv_obj_set_y(ui_versionLabel, 81);
    lv_obj_set_align(ui_versionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_versionLabel, "v1.0.0");

    ui_wifiButton = lv_btn_create(ui_confScreen);
    lv_obj_set_width(ui_wifiButton, 77);
    lv_obj_set_height(ui_wifiButton, 41);
    lv_obj_set_x(ui_wifiButton, -14);
    lv_obj_set_y(ui_wifiButton, 81);
    lv_obj_set_align(ui_wifiButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_wifiButton);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Wifi");

    ui_canonTimeContainer = lv_obj_create(ui_confScreen);
    lv_obj_remove_style_all(ui_canonTimeContainer);
    lv_obj_set_width(ui_canonTimeContainer, 305);
    lv_obj_set_height(ui_canonTimeContainer, 36);
    lv_obj_set_x(ui_canonTimeContainer, 0);
    lv_obj_set_y(ui_canonTimeContainer, -48);
    lv_obj_set_align(ui_canonTimeContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_canonTimeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_canonTimeLabel = lv_label_create(ui_canonTimeContainer);
    lv_obj_set_width(ui_canonTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_canonTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_canonTimeLabel, -27);
    lv_obj_set_y(ui_canonTimeLabel, -10);
    lv_obj_set_align(ui_canonTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_canonTimeLabel, "15");

    ui_canonTimeSlider = lv_slider_create(ui_canonTimeContainer);
    lv_slider_set_range(ui_canonTimeSlider, 10, 20);
    lv_slider_set_value(ui_canonTimeSlider, 15, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_canonTimeSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_canonTimeSlider, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_canonTimeSlider, 123);
    lv_obj_set_height(ui_canonTimeSlider, 10);
    lv_obj_set_x(ui_canonTimeSlider, 64);
    lv_obj_set_y(ui_canonTimeSlider, -8);
    lv_obj_set_align(ui_canonTimeSlider, LV_ALIGN_CENTER);


    ui_canonTimeText = lv_label_create(ui_canonTimeContainer);
    lv_obj_set_width(ui_canonTimeText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_canonTimeText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_canonTimeText, -104);
    lv_obj_set_y(ui_canonTimeText, -10);
    lv_obj_set_align(ui_canonTimeText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_canonTimeText, "Canon Time");

    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_camType, ui_event_camType, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_updateButton, ui_event_updateButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiButton, ui_event_wifiButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_canonTimeSlider, ui_event_canonTimeSlider, LV_EVENT_ALL, NULL);

}
