// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Cheap_Yello_Display_demo

#include "../ui.h"

void ui_movScreen_screen_init(void)
{
    ui_movScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_movScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_movScreen, lv_color_hex(0x8BEAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_movScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imgbtn_create(ui_movScreen);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_png, NULL);
    lv_obj_set_height(ui_ImgButton2, 36);
    lv_obj_set_width(ui_ImgButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton2, 125);
    lv_obj_set_y(ui_ImgButton2, 88);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_Label7 = lv_label_create(ui_movScreen);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -2);
    lv_obj_set_y(ui_Label7, -93);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Movimiento");

    ui_dropDownDistMov = lv_dropdown_create(ui_movScreen);
    lv_dropdown_set_dir(ui_dropDownDistMov, LV_DIR_LEFT);
    lv_dropdown_set_options(ui_dropDownDistMov, "All\n5 cm\n1 cm\n1 mm\n0,1 mm\n");
    lv_obj_set_width(ui_dropDownDistMov, 83);
    lv_obj_set_height(ui_dropDownDistMov, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dropDownDistMov, 92);
    lv_obj_set_y(ui_dropDownDistMov, -42);
    lv_obj_set_align(ui_dropDownDistMov, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dropDownDistMov, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Label9 = lv_label_create(ui_movScreen);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -51);
    lv_obj_set_y(ui_Label9, -42);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Distancia a mover");

    ui_ImgButton4 = lv_imgbtn_create(ui_movScreen);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_388382192, NULL);
    lv_obj_set_height(ui_ImgButton4, 39);
    lv_obj_set_width(ui_ImgButton4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton4, -53);
    lv_obj_set_y(ui_ImgButton4, 16);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_CENTER);

    ui_ImgButton5 = lv_imgbtn_create(ui_movScreen);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1101766569, NULL);
    lv_obj_set_height(ui_ImgButton5, 40);
    lv_obj_set_width(ui_ImgButton5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton5, 81);
    lv_obj_set_y(ui_ImgButton5, 18);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_CENTER);

    ui_movLabel = lv_label_create(ui_movScreen);
    lv_obj_set_width(ui_movLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_movLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_movLabel, 12);
    lv_obj_set_y(ui_movLabel, 74);
    lv_obj_set_align(ui_movLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_movLabel, "Stop");

    ui_ImgButton6 = lv_imgbtn_create(ui_movScreen);
    lv_imgbtn_set_src(ui_ImgButton6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_885855874, NULL);
    lv_obj_set_height(ui_ImgButton6, 36);
    lv_obj_set_width(ui_ImgButton6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ImgButton6, 16);
    lv_obj_set_y(ui_ImgButton6, 15);
    lv_obj_set_align(ui_ImgButton6, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dropDownDistMov, ui_event_dropDownDistMov, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton5, ui_event_ImgButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton6, ui_event_ImgButton6, LV_EVENT_ALL, NULL);

}
