// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Cheap_Yello_Display_demo

#include "../ui.h"

void ui_wifiScreen_screen_init(void)
{
    ui_wifiScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_wifiScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiScreen, lv_color_hex(0x8BEAEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_wifiScreen);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 132);
    lv_obj_set_height(ui_Container2, 50);
    lv_obj_set_x(ui_Container2, -82);
    lv_obj_set_y(ui_Container2, -67);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_wifiScreen);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 100);
    lv_obj_set_height(ui_Container3, 50);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ssidDropdown = lv_dropdown_create(ui_wifiScreen);
    lv_dropdown_set_options(ui_ssidDropdown, "");
    lv_obj_set_width(ui_ssidDropdown, 273);
    lv_obj_set_height(ui_ssidDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ssidDropdown, 19);
    lv_obj_set_y(ui_ssidDropdown, -87);
    lv_obj_set_align(ui_ssidDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ssidDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Label6 = lv_label_create(ui_wifiScreen);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -137);
    lv_obj_set_y(ui_Label6, -87);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "SSID");

    ui_Image3 = lv_img_create(ui_wifiScreen);
    lv_img_set_src(ui_Image3, &ui_img_home_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image3, 137);
    lv_obj_set_y(ui_Image3, 96);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiKeyboard = lv_keyboard_create(ui_wifiScreen);
    lv_obj_set_width(ui_wifiKeyboard, 300);
    lv_obj_set_height(ui_wifiKeyboard, 120);
    lv_obj_set_x(ui_wifiKeyboard, 3);
    lv_obj_set_y(ui_wifiKeyboard, 53);
    lv_obj_set_align(ui_wifiKeyboard, LV_ALIGN_CENTER);

    ui_Label8 = lv_label_create(ui_wifiScreen);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -131);
    lv_obj_set_y(ui_Label8, -41);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "PASS");

    ui_passTextarea = lv_textarea_create(ui_wifiScreen);
    lv_obj_set_width(ui_passTextarea, 228);
    lv_obj_set_height(ui_passTextarea, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(ui_passTextarea, 28);
    lv_obj_set_y(ui_passTextarea, -40);
    lv_obj_set_align(ui_passTextarea, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_passTextarea, 12);
    lv_textarea_set_one_line(ui_passTextarea, true);



    lv_obj_add_event_cb(ui_Image3, ui_event_Image3, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_wifiKeyboard, ui_passTextarea);
    lv_obj_add_event_cb(ui_wifiKeyboard, ui_event_wifiKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_passTextarea, ui_event_passTextarea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifiScreen, ui_event_wifiScreen, LV_EVENT_ALL, NULL);

}
